# print("Hello World!")
# print("Hello Again!")
# print("I like typing this.")
# print("This is fun.")
# print('Yay!printing')
# print("I'd much rather you 'not'.")
# print('I "said" do not touch this.') 
# print('"多"打一行')
print("只有'一'行")